title: Finally FOSS
description: >-
  Tracking source-available software as it transitions to open-source licenses.
baseurl: "/finally-foss"
url: "https://captnemo.in"

plugins:
  - jekyll-timeago

exclude:
  - src/
  - pyproject.toml
  - uv.lock
  - .venv/
  - "*.py"
  - release-data